### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by RensWillink** [anhbh310/gotify2telegram#9]
Hi, 

I have gotify running in an lxc on proxmox (helper scripts) and im trying to install the plugin, is there a tutorial i can follow? the installation steps are to cryptic for my experiance level.

Thank you in advance !

**Comment by RensWillink** [comment]
got it installed, receiving messages in gotify however not in telegram, followed the steps including setting the group privacy of the bot to off, where are the logs located ? the only thing i see right now is that it says never for the client i created for the plugin

**Comment by RensWillink** [comment]
alright getting closer: 

Oct 29 08:32:42 Gotify gotify-linux-amd64[146]: Cannot connect to websocket: malformed ws or wss URL

ss -lnp | grep gotify gives me:

tcp   LISTEN 0      4096                                            *:80                     *:*    users:(("gotify-linux-am",pid=146,fd=7))

i have tried various urls, my gotify runs on an lxc in proxmox ....dont know if that relevant

**Comment by RensWillink** [comment]
also as soon as i enable the plugin in gotify the cpu goes up to 100%

**Comment by anhbh310** [comment]
Hi @RensWillink, 

I've just re-created your setup (I guess you used this [lxc script](https://tteck.github.io/Proxmox/#proxmox-ve-tools)).
It’s strange because the issue only appears in the LXC environment. I figured out that the plugin receives messages from the Gotify client, but it cannot forward them to the Telegram bot API.
Just wanted to let you know that I'm working on a solution.

Thanks for your consideration!

**Comment by RensWillink** [comment]
that is great to hear, thank you for your time !!  (yes i used that script)

**Comment by RensWillink** [comment]
i dont know if it's possible, it would be great if we can use the app to forward to groups.....

**Comment by anhbh310** [comment]
Here’s a revised version for clarity and correct grammar:

Hi @RensWillink,

I've added a logger to the plugin. Could you please try the new release [v1.1.2](https://github.com/anhbh310/gotify2telegram/releases/tag/v1.1.2)? Run it and let me know if there’s anything new.

Regarding the issue with LXC, it was my mistake—I had set the chat ID variable incorrectly. After fixing the environment variables, everything works fine.

And if you want to send notifications from Gotify to a group chat, just follow these two steps:

- Add your Telegram bot to the group chat.
- Update the chat ID variable.

I tested it, and it runs perfectly.

**Comment by RensWillink** [comment]
Great! Thank you for looking in to it! I will test it in the coming days and report back here, thanks again.

**Comment by RensWillink** [comment]
Message arrives in gotify however doesnt gets forwarded to telegram. (bot works with other systems) cpu goes to 100% when plugin is enabled.

**Comment by ZanardiZZ** [comment]
Can confirm I have the same issue as RensWillink, even the 100% CPU usage.

**Comment by anhbh310** [comment]
Hi @RensWillink, could you show me the running log by using the command `journalctl -f -u gotify.service`?

**Comment by Calimerorulez** [comment]
Hi @anhbh310 

I'm having the same problem as above.

The output of your requested command is:

```
Nov 26 19:24:40 gotify gotify-linux-amd64[125]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Nov 26 19:24:40 gotify gotify-linux-amd64[125]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Nov 26 19:24:40 gotify gotify-linux-amd64[125]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Nov 26 19:24:40 gotify gotify-linux-amd64[125]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Nov 26 19:24:40 gotify gotify-linux-amd64[125]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Nov 26 19:24:40 gotify gotify-linux-amd64[125]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
```

And it keeps looping like this. Hope it helps.

**Comment by noob34433** [comment]
same thing happening with me

**Comment by RensWillink** [comment]
Sorry i was a bit busy, here is the log:

`Dec 08 12:22:48 gotify gotify-linux-amd64[150]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Dec 08 12:22:48 gotify gotify-linux-amd64[150]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Dec 08 12:22:48 gotify gotify-linux-amd64[150]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Dec 08 12:22:48 gotify gotify-linux-amd64[150]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Dec 08 12:22:48 gotify gotify-linux-amd64[150]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Dec 08 12:22:48 gotify gotify-linux-amd64[150]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Dec 08 12:22:48 gotify gotify-linux-amd64[150]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Dec 08 12:22:48 gotify gotify-linux-amd64[150]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Dec 08 12:22:48 gotify gotify-linux-amd64[150]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Dec 08 12:22:48 gotify gotify-linux-amd64[150]: Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL`

**Comment by i-montoro** [comment]
Hi @anhbh310,  I have same issue. I share all details in order to help troubleshooting.
I'm running gotify as an lxc container from  the [scripts](https://tteck.github.io/Proxmox/#proxmox-ve-tools)
After copying the plugin into the gotify plugin folder I put the following into the config.yaml

```
GOTIFY_HOST: "ws://localhost:80"
GOTIFY_CLIENT_TOKEN: "xxxxxxxxxxxxxxxx"
TELEGRAM_CHAT_ID: "xxxxxxxxxxxxxxxx"
TELEGRAM_BOT_TOKEN: "xxxxxxxxxxxxxxxxxxx"
logging:
  level: "error"
```

Then, I restart gotify service and the CPU usage is 100%, the error log file is growing so fast  filling up all disk space.
This is what I found in the log file:

```
Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: malformed ws or wss URL
```
Also I get another log file with the following information:

```
panic: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `GOTIFY_...` into config.Configuration

goroutine 1 [running]:
github.com/gotify/server/v2/config.Get()
        /proj/config/config.go:71 +0x21e
main.main()
        /proj/app.go:34 +0x1e5
```

I hope it helps a littel :+1: 

Thanks

**Comment by vv1ck3d** [comment]
the same problem with 100% cpu load and errors in log:
Error #01: you need to provide a valid access token or user credentials to access this api
Gotify 2 Telegram: plugin.go:121: Cannot connect to websocket: websocket: bad handshake
2024-12-20T16:49:27+03:00 | 401 |      78.293µs |             ::1 | GET      "/stream?token=[masked]"

gotify 2.6.1 and 1.20 plugin.

**Comment by fsLelush** [comment]
Hello, everyone. For those who also use in proxmox [this](https://community-scripts.github.io/ProxmoxVE/scripts?id=docker) lxc container with docker. I share the installation method and my compose file.
```compose.yml
version: '3'

services:
  gotify:
    container_name: gotify
    image: gotify/server
    ports:
      - 8080:80
    environment:
      GOTIFY_DEFAULTUSER_PASS: 'YOUR_PASS'
      #It didn't work for me with http/http(s). It works fine with ws
      GOTIFY_HOST: ws://YOUR_GOTIFY_IP:8080
      GOTIFY_CLIENT_TOKEN: YOUR_GOTIFY_CLIENT_TOKEN
      TELEGRAM_CHAT_ID: YOUR_CHAT_ID
      TELEGRAM_BOT_TOKEN: YOUR_TOKEN_FROM_BOTFATHER
    volumes:
      - './gotify_data:/app/data'
    restart: unless-stopped
 ```
1) Open the LXC Docker console. Enter the command:
```bash
cd "$(find / -path "*/gotify_data/plugins" -type d 2>/dev/null)"
```
2) Download the latest version of the plugin by replacing the numbers with the latest release number. At the moment of writing the latest version is 1.2.0
```bash
wget https://github.com/anhbh310/gotify2telegram/releases/download/v1.2.0/telegram-plugin-linux-amd64.so
```
3) Enable the plugin in gotify. It should work. Now can send yourself a test notification for example from uptime-kuma
![image](https://github.com/user-attachments/assets/caba3652-55e8-4521-b006-6f56db13549d)
![image](https://github.com/user-attachments/assets/eea0ad45-f6f3-4abe-a199-fff46cd5481d)

I hope this helps someone
